### ISSUE TITLE
消息发送失败

### ISSUE THREAD

**Issue by jiqiren116** [wvit/BOSS_batch_deliver#1]
大佬，显示消息已发送，但实际上并未发送，不知道是不是我一次性选择的太多的原因

**Comment by jiqiren116** [comment]
或许改一下消息发送的时间间隔，现在的时间间隔太短了，打开了对话框还没有填入打招呼语就接着打开了下一个对话框

**Comment by wvit** [comment]
好像是有这个问题，我排查一下，目前有两个方案可以绕过。 

1，你可以先暂时勾选30个以内，然后批量沟通。

2，使用boss直聘平台配置的招呼语，这样应该可以一次大批量沟通。

**Comment by wvit** [comment]
> 改一下可能消息发送的时间间隔，现在的时间间隔太短了，打开了对话框还没有填入打招呼语就连接打开了下一个对话框

想要有这个问题，我排查了一下，目前有两个方案可以绕过。

1，你可以先暂时勾选30个以内，然后批量协调。

2，使用老板聘直平台配置的招呼语，这样应该可以进行一次大批量沟通

**Comment by wvit** [comment]
> 改一下可能消息发送的时间间隔，现在的时间间隔太短了，打开了对话框还没有填入打招呼语就连接了打开下一个对话框

好像是有这个问题，我排查了一下，目前有两个方案可以绕过。

1，你可以先暂时勾选30个以内，然后批量调整。

2，使用老板聘直平台配置的招呼语，这样应该可以进行一次大批量沟通

**Comment by wvit** [comment]
> 改一下可能消息发送的时间间隔，现在的时间间隔太短了，打开了对话框还没有填入打招呼语就连接了打开下一个对话框

1，你可以先暂时勾选30个以内，然后开始批量沟通。

2，使用老板聘直平台配置的招呼语，这样应该可以进行一次大批量沟通。

**Comment by wvit** [comment]
> 或许改一下消息发送的时间间隔，现在的时间间隔太短了，打开了对话框还没有填入打招呼语就接着打开了下一个对话框

好像是有这个问题，我排查一下，目前有两个方案可以绕过这个问题：

1，你可以先暂时勾选30个以内，然后批量调整。

2，使用老板聘直平台配置的招呼语，这样应该可以进行一次大批量沟通

**Comment by wvit** [comment]
> 或许改一下消息发送的时间间隔，现在的时间间隔太短了，打开了对话框还没有填入打招呼语就接着打开了下一个对话框

好像是有这个问题，我排查一下，目前有两个方案可以绕过这个问题：

1，你可以先暂时勾选30个以内，然后批量调整。

2，使用boss直聘平台配置的招呼语，这样应该可以进行一次大批量沟通。

**Comment by wvit** [comment]
你好，你可以下载最新的“chorme-extension.zip”测试一下，我在最新版本中，做了一些发送消息的优化：

1，每沟通完 20 个职位后，会关闭当前发送消息的浏览器窗口，然后等待 2s 后再新开一个窗口继续发送消息，直到发送完成。

2，优化了一下发送消息的定时器，以前是固定等待 0.5s ，现在改为等待0.2s ～3s。

我发现当发送到 25条左右 后，发送失败的概率会提升，到了最后甚至很多消息都发送失败了，感觉这不是客户端（插件）的问题。

所以我做了一些优化，添加窗口的重新打开 和 调整定时器逻辑，是为了给 boss直聘服务器一个缓冲的时间。
我再次测试后，发送失败的问题得到了一定的优化。

如果还是有问题你可以：

**Comment by wvit** [comment]
你好，你可以下载最新的“chorme-extension.zip”测试一下，我在最新版本中，做了一些发送消息的优化：

1，每沟通完 20 个职位后，会关闭当前发送消息的浏览器窗口，然后等待 2s 后再新开一个窗口继续发送消息，直到发送完成。

2，优化了一下发送消息的定时器，以前是固定等待 0.5s ，现在改为等待0.2s ～3s。

我发现当发送到 25条左右 后，发送失败的概率会提升，到了最后甚至很多消息都发送失败了，感觉这不是客户端（插件）的问题。

所以我做了一些优化，添加窗口的重新打开 和 调整定时器逻辑，是为了给 boss直聘服务器一个缓冲的时间。
我再次测试后，发送失败的问题得到了一定的优化。

如果还是有问题可以继续向我反馈，或者试试以下办法：

1，尝试关闭网络代理。

2，一次批量的数据最大在 30条 左右。

3，开启平台的“打招呼语”配置，这样就直接使用了招呼语。

**Comment by jiqiren116** [comment]
确实，当前成功率最高的是使用平台默认的打招呼语，使用自己设置的打招呼语还是总是失败，当前也只能这样了，感谢大佬的付出！！

**Comment by wvit** [comment]
> 确实，当前成功率最高的是使用平台默认的打招呼语，使用自己设置的打招呼语还是总是失败，当前也只能这样了，感谢大佬的付出！！

请问是一开始批量沟通就失败吗，我大概是沟通30条后失败率才大幅提升的。

**Comment by jiqiren116** [comment]
emm，这次尝试了一下，基本一开始批量沟通就失败了，就像图片所示，发送了十条只有前几条是成功的，用默认招呼语就没有这种情况，但是你是差不多30条后才会失败，所以可能是我这边的网络原因或者是其他原因吧（但我在用插件的时候并没有挂梯子）。
<img width="578" alt="1711684863571" src="https://github.com/wvit/BOSS_batch_deliver/assets/71168040/fb563cbd-1224-4468-aef6-3030d6d13317">

**Comment by wvit** [comment]
你好，我有意向研究一下这个问题，如果你愿意的话可以加一下我的微信， “vvvwv-o_o-”， github 沟通有些延时。

**Comment by wvit** [comment]
> emm，这次尝试了一下，基本一开始批量沟通就失败了，就像图片所示，发送了十条只有前几条是成功的，用默认招呼语就没有这种情况，但是你是差不多30条后才会失败，所以可能是我这边的网络原因或者是其他原因吧（但我在用插件的时候并没有挂梯子）。 <img alt="1711684863571" width="578" src="https://private-user-images.githubusercontent.com/71168040/317949962-fb563cbd-1224-4468-aef6-3030d6d13317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NzczMjEsIm5iZiI6MTcxMTc3NzAyMSwicGF0aCI6Ii83MTE2ODA0MC8zMTc5NDk5NjItZmI1NjNjYmQtMTIyNC00NDY4LWFlZjYtMzAzMGQ2ZDEzMzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA1MzcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZTRmMjc3NGRlYzg3YzQxZjk0MjQ3MDA4ZGQyOTc3YmIyNDhmODNiZmUxMTdkOWM4MGViZTE3YTAzY2I0ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uyDlTJQEvYUx4xZE9Dz8XwuqROIYRoWf83WWKcpjDnA">


你好，我有意向研究一下这个问题，如果你愿意的话可以加一下我的微信， “vvvwv-o_o-”， github 沟通有些延时。

**Comment by jiqiren116** [comment]
> > emm，这次尝试了一下，基本一开始批量沟通就失败了，就像图片所示，发送了十条只有前几条是成功的，用默认招呼语就没有这种情况，但是你是差不多30条后才会失败，所以可能是我这边的网络原因或者是其他原因吧（但我在用插件的时候并没有挂梯子）。 <img alt="1711684863571" width="578" src="https://private-user-images.githubusercontent.com/71168040/317949962-fb563cbd-1224-4468-aef6-3030d6d13317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NzczMjEsIm5iZiI6MTcxMTc3NzAyMSwicGF0aCI6Ii83MTE2ODA0MC8zMTc5NDk5NjItZmI1NjNjYmQtMTIyNC00NDY4LWFlZjYtMzAzMGQ2ZDEzMzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA1MzcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZTRmMjc3NGRlYzg3YzQxZjk0MjQ3MDA4ZGQyOTc3YmIyNDhmODNiZmUxMTdkOWM4MGViZTE3YTAzY2I0ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uyDlTJQEvYUx4xZE9Dz8XwuqROIYRoWf83WWKcpjDnA">
> 
> 你好，我有意向研究一下这个问题，如果你愿意的话可以加一下我的微信， “vvvwv-o_o-”， github 沟通有些延时。

ok

**Comment by wvit** [comment]
已添加间隔时间选项，如果需要可以尝试此配置

<img width="368" alt="image" src="https://github.com/wvit/BOSS_batch_deliver/assets/21981758/5abab3f2-fece-4c36-a163-68d5b89f5cd0">

**Comment by jiqiren116** [comment]
> 已添加间隔时间选项，如果需要可以尝试此配置
> 
> <img alt="image" width="368" src="https://private-user-images.githubusercontent.com/21981758/322007837-5abab3f2-fece-4c36-a163-68d5b89f5cd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTU3NzksIm5iZiI6MTcxODA5NTQ3OSwicGF0aCI6Ii8yMTk4MTc1OC8zMjIwMDc4MzctNWFiYWIzZjItZmVjZS00YzM2LWExNjMtNjhkNWI4OWY1Y2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA4NDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MzI0YmEyZDc4OGVlM2NhZDBiMjk1Njc5MWYwYTkwMTBlNDVkZTk3MGJmNWM3ODdlMjg5MGEzMWRkYjNlODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZksWt4-_v2K_PHn11P4rAWJgzxfIIfgneO87Chlrc40">

抱歉这么晚才回复，很感谢您的插件，已经找到工作了，这个插件确实帮了我很多

**Comment by chen3252yb** [comment]
不能用了，即使跳转过后依旧显示需要跳转，不知道是不是网站屏蔽了

**Comment by wvit** [comment]
好的，我检查一下

**Comment by wvit** [comment]
> 不能用了，即使跳转过后依旧显示需要跳转，不知道是不是网站屏蔽了

好的，我检查一下
